blank_issues_enabled: false
contact_links:
  - name: Không có tài khoản Github? Không biết dùng Github?
    url: https://ybw0014.net/go/sf-qgroup
    about: Nhấn nút bên phải để tham gia nhóm QQ phản hồi
